apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "airlift.statePvcName" . }}
  labels:
    {{- include "airlift.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.state.size | quote }}
  {{- with .Values.state.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
