{{- if and (not .Values.artifactory.existingSecret) (not .Values.artifactory.tokenFile.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airlift.secretName" . }}
  labels:
    {{- include "airlift.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.artifactory.token | quote }}
  username: {{ .Values.artifactory.username | quote }}
  password: {{ .Values.artifactory.password | quote }}
{{- end }}
